---
output: github_document
params:
  github_username: "Lightbridge-KS"
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include=FALSE}
here::i_am("README.Rmd")
library(here)
source(here("R/gh_stats_card.R"))
source(here("R/gh_top_lang_card.R"))
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Lightbridge-KS





<!-- Github Stats by "https://github.com/anuraghazra/github-readme-stats" -->

```{r my_stats_card, include=FALSE}
# Stats Card
my_stats_card <- gh_stats_card(params$github_username, 
                               count_private = TRUE, 
                               show_icons = TRUE, 
                               theme = "radical")
```


<!-- GitHub Stats Card: Start -->
`r my_stats_card`
<!-- GitHub Stats Card: End -->


```{r my_top_lang_card, include=FALSE}
# Top Language Card
my_top_lang_card <- gh_top_lang_card(params$github_username,
                                     hide = "html",
                                     layout_compact = TRUE)
```


<!-- Github Top Languages Card: Start -->
`r my_top_lang_card`
<!-- Github Top Languages Card: End -->

